[ATP-294] Implement work manager
sdvkit/PexelsApp pull request #13
Opened 2024-02-14 07:56 UTC by sdvkit

Implement work manager to the project to send notifications.

![Screenshot_20240214_085047](https://github.com/sdvkit/PexelsApp/assets/101420114/5255020d-67f9-40a4-a6a5-d397f43abb8a)

![Screenshot_20240214_085528](https://github.com/sdvkit/PexelsApp/assets/101420114/c1b2834e-fbbf-497b-8b61-8b5e9dd3db89)

2024-02-14 15:11 UTC, VladislavShi commented on app/src/main/java/com/sdv/kit/pexelsapp/presentation/worker/DailyCheckPhotosWorker.kt
> +            notificationId = 2,
by the way lets create some constants, where we can store those ids

2024-02-15 12:46 UTC, sdvkit commented on app/src/main/java/com/sdv/kit/pexelsapp/presentation/worker/DailyCheckPhotosWorker.kt
> +            notificationId = 2,
Ok

2024-02-15 13:02 UTC, VladislavShi requested changes

2024-02-15 13:02 UTC, VladislavShi commented on app/src/main/java/com/sdv/kit/pexelsapp/data/manager/NotificationManagerImpl.kt
> -    companion object {
Return this to companion object, notification constants we need in one place for better understanding which constant for what notification

2024-02-15 13:07 UTC, VladislavShi approved these changes
All good for me

2024-02-15 13:23 UTC, merged