[ATP-300] Implement camera
sdvkit/PexelsApp pull request #17
Opened 2024-02-19 13:31 UTC by sdvkit

Working camera functionality on profile screen

2024-02-20 09:45 UTC, VladislavShi requested changes

2024-02-20 09:45 UTC, VladislavShi commented on app/src/main/java/com/sdv/kit/pexelsapp/data/manager/PermissionEntryManagerImpl.kt
> +        with(sharedPreferences.edit()) {
Why not write like this? 
![image](https://github.com/sdvkit/PexelsApp/assets/133751754/04f5355f-8c82-423c-bef8-0b1ed7c20a13)

2024-02-20 15:40 UTC, sdvkit commented on app/src/main/java/com/sdv/kit/pexelsapp/data/manager/PermissionEntryManagerImpl.kt
> +        with(sharedPreferences.edit()) {
It's a sample code from this article [https://developer.android.com/training/data-storage/shared-preferences]

2024-02-20 15:49 UTC, sdvkit commented on app/src/main/java/com/sdv/kit/pexelsapp/presentation/profile/ProfileViewModel.kt
> +        viewModelScope.launch {
I can only add Disptacher.Main because of this exception:
![image](https://github.com/sdvkit/PexelsApp/assets/101420114/2e0c3ee9-3cc4-4554-9f4c-873a1b50ce2c)

2024-02-20 15:56 UTC, sdvkit commented on app/src/main/java/com/sdv/kit/pexelsapp/data/manager/PermissionEntryManagerImpl.kt
> +        with(sharedPreferences.edit()) {
If necessary I can change it

2024-02-21 13:12 UTC, VladislavShi approved these changes
Everything is fine

2024-02-21 13:14 UTC, merged